stages:
  prepare:
    cmd: >
      uv run torchbiggraph_import_from_tsv
      --lhs-col=${import_data.lhs_col}
      --rel-col=${import_data.rel_col}
      --rhs-col=${import_data.rhs_col}
      ${import_data.config_path}
      ${import_data.train_path}
      ${import_data.test_path}
    deps:
      - ${import_data.config_path}
      - ${import_data.train_path}
      - ${import_data.test_path}
    outs:
      - ${entity_path}
 
  train:
    matrix:
      comparator: ${train.scoring_model.comparator}
    cmd: >
      mkdir -p logs && uv run torchbiggraph_train
      ${train.config_path}
      -p comparator=${item.comparator}
      -p workers=${train.workers}
      -p checkpoint_path=results/${item.comparator}_${operator}_checkpoint
      -p edge_paths=${edge_paths.train} > logs/${key}_train.log
    deps:
      - ${train.config_path}
      - ${entity_path}
    outs:
      - results/${item.comparator}_${operator}_checkpoint

  eval_collect_epochs:
    matrix:
      comparator: ${train.scoring_model.comparator}
    cmd: >
      ./tasks/eval_collect_epochs.sh
      --config ${train.config_path}
      --checkpoint-root results/${item.comparator}_${operator}_checkpoint
      --entity-path ${entity_path}
      --workers ${train.workers}
      --operator ${operator}
      --comparator ${item.comparator}
      --edge-samples train,test
    deps:
      - tasks/eval_collect_epochs.sh
      - tasks/awk_parse_metrics.sh
      - results/${item.comparator}_${operator}_checkpoint
      - ${train.config_path}
      - ${entity_path}/train_partitioned
      - ${entity_path}/test_partitioned
    outs:
      - logs/eval_${operator}_${item.comparator}
    metrics:
      - metrics/eval_${operator}_${item.comparator}_all_epochs.json


